export const BINGO_SELECT = "BINGO_SELECT";
export const BINGO_PLAY_ANIMATION = "BINGO_PLAY_ANIMATION";
export const BINGO_PAUSE_ANIMATION = "BINGO_PAUSE_ANIMATION";
export const BINGO_REPLAY_ANIMATION = "BINGO_REPLAY_ANIMATION";
export const BINGO_RESET = "BINGO_RESET";
export const BINGO_NEW = "BINGO_NEW";
export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const BINGO_DESELECT = "BINGO_DESELECT";